volumes:
  kestra-data:
    driver: local
  postgres-data:
    driver: local
  project-data:
    driver: local  # New volume for the project database

services:
  postgres-kestra:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"

  postgres-f1:  # New service for your project database
    image: postgres
    volumes:
      - project-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drive_to_survive  # Name of the new database
      POSTGRES_USER: f1_user  # User for the project database
      POSTGRES_PASSWORD: drivetosurvive  # Password for the project user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "5433:5432"  # Expose a different port for the project database (5433 on the host)

  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      SECRET_GITHUB_TOKEN: ${SECRET_GITHUB_TOKEN}
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres-kestra:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              enabled: true
              username: "greglenane@gmail.com"
              password: drivetosurvive
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
          tutorial-flows:
            enabled: false
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres-kestra:
        condition: service_started