name: Run Python Script with uv

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        run: uv python install

      - name: "Install dependencies"
        run: uv sync --frozen

      - name: "Run Script"
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
        run: uv run drive-to-survive-etl.py