<<<<<<< HEAD
<<<<<<< HEAD
name: Run Python Script with uv

on:
  # This enables the "Run workflow" button in the GitHub Actions tab
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 'latest'

      - name: "Set up Python"
        run: uv python install

      - name: "Install dependencies"
        run: uv sync --no-install-project

      - name: Debug File List
        run: ls -R

      - name: "Run API Script"
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
        run: uv run download-last-race.py

      - name: "Run Conversion Script"
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
        run: uv run convert-results.py
=======
name: CI
=======
name: Run Python Script with uv
>>>>>>> 811a1e9 (updates for secret use and first script run test)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
    
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
>>>>>>> 9e1b6e9 (reorg github actions file)
=======
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        run: uv python install

      - name: "Install dependencies"
        run: uv sync --frozen

      - name: "Run Script"
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
        run: uv run drive-to-survive-etl.py
>>>>>>> 811a1e9 (updates for secret use and first script run test)
